name: SecretTest.
run-name: ${{ github.actor }} is learning GitHub Actions
on: [pull_request]
jobs:
  default-env-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Test secret
        env :
          title: ${{ github.event.pull_request.title }}
        run: |
          DEVOPS = "${{secrets.MYFIRSTSECRET}}" #Get the secret in an environement variable
          echo $DEVOPS #try to show the secret but you can't because it is encrypted
          if [ "NoneOfYourBusiness" == "$DEVOPS" ]; then   #compare the secret to the pull request title. It is not supposed to be used like that but just to show what you can do.
          echo "You got the secret !"
          exit 0
          else
          echo "Secret error!"
          exit 1
          fi
